### ISSUE TITLE
Doesn't run on arm64 RasPi

### ISSUE THREAD

**Issue by flocko-motion** [nicolasbock/rabbitmq-server-snap#42]
From reading the snapcraft.yaml I assume, that the server should run on an arm64 Raspberry Pi. The service doesn't work, though:

```
[13:17:47]fmnoel@ubuntu/raspi:~$ snap logs rabbitmq-server-snap
2022-08-12T13:17:41Z systemd[1]: snap.rabbitmq-server-snap.rabbitmq-server.service: Control process exited, code=exited, status=2/INVALIDARGUMENT
2022-08-12T13:17:41Z systemd[1]: snap.rabbitmq-server-snap.rabbitmq-server.service: Failed with result 'exit-code'.
2022-08-12T13:17:51Z systemd[1]: snap.rabbitmq-server-snap.rabbitmq-server.service: Scheduled restart job, restart counter is at 384.
2022-08-12T13:17:51Z systemd[1]: Stopped Service for snap application rabbitmq-server-snap.rabbitmq-server.
2022-08-12T13:17:51Z systemd[1]: Started Service for snap application rabbitmq-server-snap.rabbitmq-server.
2022-08-12T13:17:52Z rabbitmq-server-snap.rabbitmq-server[79201]: /snap/rabbitmq-server-snap/26/usr/bin/erl: 29: exec: /snap/rabbitmq-server-snap/26/usr/bin/../lib/erlang/erts-9.3.3.15/bin/erlexec: Exec format error
2022-08-12T13:17:52Z rabbitmq-server-snap.rabbitmq-server[79209]: /snap/rabbitmq-server-snap/26/usr/bin/erl: 29: exec: /snap/rabbitmq-server-snap/26/usr/bin/../lib/erlang/erts-9.3.3.15/bin/erlexec: Exec format error
2022-08-12T13:17:52Z rabbitmq-server-snap.rabbitmq-server[79216]: /snap/rabbitmq-server-snap/26/usr/bin/erl: 29: exec: /snap/rabbitmq-server-snap/26/usr/bin/../lib/erlang/erts-9.3.3.15/bin/erlexec: Exec format error
2022-08-12T13:17:52Z systemd[1]: snap.rabbitmq-server-snap.rabbitmq-server.service: Control process exited, code=exited, status=2/INVALIDARGUMENT
2022-08-12T13:17:52Z systemd[1]: snap.rabbitmq-server-snap.rabbitmq-server.service: Failed with result 'exit-code'.
[13:17:56]fmnoel@ubuntu/raspi:~$ 
```

There's very little that a user can do wrong when starting a snap, so I assume, the build has a problem. I will investigate the problem and send a pull request, if I find a solution.

**Comment by nicolasbock** [comment]
Thanks for reporting this issue @flocko-motion ! You are right that the snap should just work and the sure can't really do anything wrong.

I'll have a look at this as well.

**Comment by flocko-motion** [comment]
It seems, that `erlexec` is not running on ARM. Maybe the x86 version is used on ARM, too? 

This is what happens, when i enter the snap using `run --shell` and try to start `erlexec`:

```
root@ubuntu:/snap/rabbitmq-server-snap/26# $SNAP/usr/lib/erlang/erts-9.3.3.15/bin/erlexec
bash: /snap/rabbitmq-server-snap/26/usr/lib/erlang/erts-9.3.3.15/bin/erlexec: cannot execute binary file: Exec format error
```

**Comment by nicolasbock** [comment]
That's strange. `Erlang` is built from source and I would not expect such an issue. But then again the error message is pretty clear :/

Unfortunately I don't have access to ARM hardware and can't test anything on ARM directly. I'll do some research into what might be going on here.

**Comment by flocko-motion** [comment]
The problem is: if you specify `- build-on: [amd64, i386, arm64]`, you excpect snapcraft to actually build on those three platforms. It used to do that in (very) old versions, but it doesn't any more. In the end you get a snap, which pretends to be multiarch, but isn't (all binaries will be strictly x86). 

I'm now working on a snapcraft.yaml which builds an arm64 only snap with the latest version of rabbitmq. I'm using precompiled binaries with the snapcraft `dump` plugin, which greatly speeds up the build process. Cross compiling for arm on x86 is very painful with snapcraft, so this seemed to be the easier path. If I trust the sources of the developers, I can also trust the binaries from the same developers published on the same git repo.

Once that's work, I might (or might not - depending on time budgets) extend it to multiarch.

I will publish my results as a fork. If you're interested, you're welcome to use any or all of them.

**Comment by nicolasbock** [comment]
Have you tried something like #46 ?

**Comment by flocko-motion** [comment]
Building arm on arm? Yes, but I don't like it at all.

There's currently no good way to build for arm - which is a pity, as I need to build a lot of snaps for arm machines.

- The proposed way is using an arm machine, but those are not available in CI/CD environments.
- Snapcraft used to build on an arm VM, but that option is long gone and never worked inside of CI/CD 
- Cross-compiling shouldn't be done

Using precompiled binaries for arm seems to be the only rational choice at the moment. Unless I miss something..?

**Comment by flocko-motion** [comment]
This seems to work, server is starting up nicely on RasPi without any errors.

https://github.com/flocko-motion/rabbitmq-server-snap

Will run tests with real clients tomorrow.

**Comment by nicolasbock** [comment]
Thanks! I'll have a look at your fork.

The lack of arm for CI/CD is unfortunate, I completely agree with you.

**Comment by flocko-motion** [comment]
I forked the project to my companies repo, where I will maintain the version:

https://github.com/ML-PA-Consulting-GmbH/rabbitmq-server-snap

The version on my personal page will not be updated any more.

**Comment by nicolasbock** [comment]
Thanks for the info! And thanks for the help!

**Comment by flocko-motion** [comment]
All build scripts now work, snaps were manually tested on arm64 and amd64. CI/CD automatically creates releases on GitHub (but not pushing to snapstore). I included your tests from your repos CI and they all pass (at least for amd64.. i manually performed the same tests on my RasPi and they work there, too).
As already mentioned, I will keep maintaining this version, as I need it for many other projects. As we're not going to use the Canonical snapstore, I want to ask you, if:
a) you want to update your repo independently and keep publishing it to the snapstore
b) you merge my updates into your repo and keep publishing your build to the snapstore
c) you think that I should instead publish my version to the snapstore, so other people can use it
The last option is a bit of extra work on my side, but it's good to give something back to the OSS community, right? Tell me what you think, please..

**Comment by nicolasbock** [comment]
Thanks for testing the `arm64` builds!

Regarding your questions

> you excpect snapcraft to actually build on those three platforms

Looking at the build output I see that `amd64` is built on
```
Kernel version: Linux lcy02-amd64-025 5.4.0-124-generic #140-Ubuntu SMP Thu Aug 4 02:23:37 UTC 2022 x86_64
```
and `arm64` on
```
Kernel version: Linux bos02-arm64-033 5.4.0-124-generic #140-Ubuntu SMP Thu Aug 4 02:27:01 UTC 2022 aarch64
```

That doesn't look like it's cross compiling or producing a multiarch snap. Am I missing something?

> a) you want to update your repo independently and keep publishing it to the snapstore

I would like to support all targets supported by the snap store. Erlang does not offer pre-compiled binaries for all of those platforms unfortunately which means that the snap will have to either use the Ubuntu package or build from source. Since RabbitMQ has rather tight dependencies on the exact version of Erlang Ubuntu packages will not work if we also want to be able to support the most recent RabbitMQ version.

Having said all that I intend to keep maintaining this repository and publish that to the snapstore.

> c) you think that I should instead publish my version to the snapstore, so other people can use it

That depends on your answer to my first question regarding cross compile or multiarch :smile: It would be awesome if you could test https://snapcraft.io/rabbitmq-server-snap on `arm64` and see whether it actually works or not. Unfortunately I don't have access to any arm hardware and can't test this myself. I wasn't aware for example that the multarch snap that I was publishing so far wasn't working 😞 

I am working on bumping the RabbitMQ version. I will push a PR for it very soon.

Thanks again for all your help here!

**Comment by flocko-motion** [comment]
I think you found a solution! While the old version wasn't running on arm (see beginning of this thread), the new one is!

I tested the updated `rabbitmq-server-snap` on both my arm64 raspi (ubuntu core 20) and my x86 laptop (kubuntu 20). I shelled into the snap both times and executed the erlang binaries directly - both work. I could also see in the file structure, that the raspi snap contains arm libraries, while the x86 snap contains x86 binaries. 

That's great :) 

I'm not sure yet, how you could build an arm-snap without cross-compilation on a non-arm machine. Maybe it's because you're building on core 18? I'm pretty sure that building with arm emulator (that's what needs to happen in the background, if you're not cross compiling afaik) is not available when building on core 20. Canonical wrote somewhere, that emulation had too many problems and they now only offer remote-compiling for non-native builds. 

When I build using your repo, all I get is a single arch snap for amd64. How is the arm build done? How do I initiate it?

**Comment by nicolasbock** [comment]
Thanks for testing @flocko-motion !

The build here on GitHub is just for CI purposes. I store the snap artifact simply so that I can download and install it in case I need to verify something with the CI. The "official" snaps are all built on snapcraft. The build farm is not cross compiling and running on the architecture that is requested. Since I have listed all of the supported architectures in https://github.com/nicolasbock/rabbitmq-server-snap/blob/main/snap/snapcraft.yaml#L15 all of the snaps are built on and for the architectures in that list.

**Comment by nicolasbock** [comment]
@flocko-motion Can I close this issue?

**Comment by flocko-motion** [comment]
Yes, it works now - congratulations and thanks!

Nicolas Bock ***@***.***> schrieb am Di., 6. Sept. 2022,
19:20:

**Comment by nicolasbock** [comment]
Thanks for your help!
