### ISSUE TITLE
Build script is using very old version of RabbitMQ - usage strongly discouraged by devs

### ISSUE THREAD

**Issue by flocko-motion** [nicolasbock/rabbitmq-server-snap#43]
The snapcraft.yaml is build a very old version of RabbitMQ (2015). It reached end of life 2018-05-31 and its usage is _strongly discouraged_ according to the developers (source: https://www.rabbitmq.com/which-erlang.html#eol-series)

The snap from this build should therefore not be used in any production environment until bumped to a more recent version.

**Comment by nicolasbock** [comment]
Hi @flocko-motion . I will bump the RabbitMQ version.

**Comment by nicolasbock** [comment]
I bumped RabbitMQ to version `3.8.35`. I am doing this in little steps, which is why I am not yet at anything beyond `3.8.x`. I would like to switch to a more recent `core` before I bump the RabbitMQ version again.
